In [17]:
import numpy as np
import pandas as pd
import seaborn as sns

# Problem 7

In [4]:
ames_df = pd.read_csv('data/ames_prices.csv')

In [5]:
ames_df.head()

,Order,PID,area,price,MS.SubClass,MS.Zoning,Lot.Frontage,Lot.Area,Street,Alley,...,Screen.Porch,Pool.Area,Pool.QC,Fence,Misc.Feature,Misc.Val,Mo.Sold,Yr.Sold,Sale.Type,Sale.Condition
0,1,526301100,1656,215000,20,RL,141.0,31770,Pave,NaN,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal
1,2,526350040,896,105000,20,RH,80.0,11622,Pave,NaN,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
2,3,526351010,1329,172000,20,RL,81.0,14267,Pave,NaN,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
3,4,526353030,2110,244000,20,RL,93.0,11160,Pave,NaN,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
4,5,527105010,1629,189900,60,RL,74.0,13830,Pave,NaN,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal

**a)**

In [8]:
ames_df['I.Central.Air'] = (ames_df['Central.Air'] == 'Y').astype(int)

In [34]:
ames_ca_mean = ames_df['I.Central.Air'].mean()
ames_ca_mean

np.float64(0.9331058020477816)

**b)**

In [23]:
## Bootstrapping:
R = 2_000
ca_means = []

for t in range(R):
    # Resample:
    df_ames_bs = ames_df.sample(frac=1, replace=True, random_state=t)

    # Evaluate mean:
    ca_mean = df_ames_bs['I.Central.Air'].mean()

    #Record mean
    ca_means.append(ca_mean)

**c)**

In [38]:
ca_se = np.std(ca_means, ddof=1)
ca_se

np.float64(0.004688192249670651)

**d)**

In [48]:
def ci_creator(avg, se):
    ci_90 = np.append(avg - 1.645*se, avg + 1.645*se)
    ci_95 = np.append(avg - 1.96*se, avg + 1.96*se)
    ci_99 = np.append(avg - 2.576*se, avg + 2.576*se)

    print(f'90% CI: {ci_90}\n95% CI: {ci_95}\n99% CI: {ci_99}')

In [49]:
ci_creator(ames_ca_mean, ca_se)

90% CI: [0.92539373 0.94081788]
95% CI: [0.92391695 0.94229466]
99% CI: [0.92102902 0.94518259]

**e)**

- p = .90 does not fall within any of the confidence intervals at significance levels $\alpha$ = .10, .05 or .01. Therefore, we reject the null hypothesis at each significance level

# Problem 8

In [59]:
ames_df['arcsinh_area'] = np.arcsinh(ames_df['area'])
ames_df['arcsinh_price'] = np.arcsinh(ames_df['price'])
correlation = ames_df['arcsinh_area'].corr(ames_df['arcsinh_price'])
print(correlation)

0.7231661530091356

**a)**

In [63]:
R = 2_000
corr_values = []

for t in range(R):
    # Resample:
    df_ames_bs = ames_df.sample(frac=1, replace=True, random_state=t)

    # Evaluate corr:
    corr = df_ames_bs['arcsinh_area'].corr(df_ames_bs['arcsinh_price'])

    #Record corr:
    corr_values.append(corr)

**b)**

In [65]:
corr_se = np.std(corr_values, ddof=1)
corr_se

np.float64(0.010160928394036659)

**c)**

In [67]:
ci_creator(correlation, corr_se)

90% CI: [0.70645143 0.73988088]
95% CI: [0.70325073 0.74308157]
99% CI: [0.6969916 0.7493407]

# Problem 9

**a)**

In [68]:
metabric_df = pd.read_csv('data/metabric.csv')

In [75]:
survival_mean = metabric_df['Overall Survival (Months)'].mean()
survival_mean

np.float64(129.09429138744105)

**b)**

In [76]:
## Bootstrapping:
R = 2_000
survival_means = []

for t in range(R):
    # Resample:
    metabric_bs = metabric_df.sample(frac=1, replace=True, random_state=t)

    # Evaluate mean:
    survival_mean = metabric_bs['Overall Survival (Months)'].mean()

    #Record mean
    survival_means.append(survival_mean)

**c)**

In [78]:
survival_se = np.std(survival_means, ddof=1)
survival_se

np.float64(2.13388484082875)

**d)**

In [79]:
ci_creator(survival_mean, survival_se)

90% CI: [121.90894534 128.92942647]
95% CI: [121.23677161 129.60160019]
99% CI: [119.92229855 130.91607325]

# Problem 10

In [81]:
sleep_df = pd.read_csv('data/nhanes_data_17_18.csv')
sleep_df

C:\Users\sjy3p\AppData\Local\Temp\ipykernel_800\3000062724.py:1: DtypeWarning: Columns (0: ServedActiveDutyInUsArmedForces) have mixed types. Specify dtype option on import or set low_memory=False.
  sleep_df = pd.read_csv('data/nhanes_data_17_18.csv')

,SEQN,GeneralHealthCondition,EverBreastfedOrFedBreastmilk,AgeStoppedBreastfeedingdays,AgeFirstFedFormuladays,AgeStoppedReceivingFormuladays,AgeStartedOtherFoodbeverage,AgeFirstFedMilkdays,TypeOfMilkFirstFedWholeMilk,TypeOfMilkFirstFed2Milk,...,DaysSmokedCigsDuringPast30Days,AvgCigarettesdayDuringPast30Days,TriedToQuitSmoking,TimesStoppedSmokingCigarettes,HowLongWereYouAbleToStopSmoking,UnitOfMeasureDayweekmonthyear_2_SMQ,CurrentSelfreportedHeightInches,CurrentSelfreportedWeightPounds,TriedToLoseWeightInPastYear,TimesLost10LbsOrMoreToLoseWeight
0,93703.0,NaN,1.0,273.0,1.0,365.0,152.0,365.0,Whole or regular milk,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93704.0,NaN,1.0,60.0,3.0,365.0,126.0,365.0,Whole or regular milk,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93705.0,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,63.0,165.0,0.0,11 times or more
3,93706.0,Very good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,68.0,145.0,0.0,Never
4,93707.0,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8361,102952.0,Very good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117.0,0.0,Never
8362,102953.0,Fair or,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,65.0,218.0,0.0,Never
8363,102954.0,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,66.0,150.0,0.0,Never
8364,102955.0,Very good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8365,102956.0,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.0,20.0,1.0,1.0,2.0,Days,69.0,250.0,0.0,1 to 2